# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

# Builds everything.
all: all-hello-world

# Cleans everything.
clean: clean-hello-world

# Builds hello-world.
all-hello-world:
	$(MAKE) -C hello-world all

# Cleans hello-world.
clean-hello-world:
	$(MAKE) -C hello-world clean
